{
    "openapi": "3.0.0",
    "info": {
        "version": "0.0.1",
        "title": "Rustywiki API",
        "description": "서버 측 API를 정의하고 공유하기 위한 문서입니다."
    },
    "servers": [
        {
            "url": "http://127.0.0.1:11111",
            "description": "no"
        }
    ],
    "components": {
        "securitySchemes": {
            "identity_server_auth": {
                "type": "oauth2",
                "flows": {
                    "implicit": {
                        "authorizationUrl": "https://demo.identityserver.io/connect/authorize",
                        "scopes": {
                            "api": "api"
                        }
                    }
                }
            }
        }
    },
    "security": [
        {
            "identity_server_auth": ["api"]
        }
    ],
    "tags": [
        {
            "name": "auth",
            "description": "인증 관련"
        },
        {
            "name": "user",
            "description": "사용자 자신 정보 관련"
        },
        {
            "name": "file",
            "description": "파일 관련"
        },
        {
            "name": "doc",
            "description": "문서 관련"
        },
        {
            "name": "search",
            "description": "검색 관련"
        }
    ],
    "paths": {
        "/auth/signup": {
            "post": {
                "tags": ["auth"],
                "summary": "회원가입입니다.",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "in": "body",
                        "name": "email",
                        "required": true,
                        "type": "string",
                        "description": "사용자 아이디(이메일)"
                    },
                    {
                        "in": "body",
                        "name": "password",
                        "required": true,
                        "type": "string",
                        "description": "사용자 패스워드"
                    },
                    {
                        "in": "body",
                        "name": "nickname",
                        "required": true,
                        "type": "string",
                        "description": "닉네임. (30자 이하)"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success=성공. email_duplicated=이메일중복. message=메세지",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "success": true,
                                        "email_duplicated": false,
                                        "message": ""
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Parameter",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {}
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {}
                                }
                            }
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "tags": ["auth"],
                "summary": "로그인입니다.",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "in": "body",
                        "name": "email",
                        "required": true,
                        "type": "string",
                        "description": "사용자 아이디(이메일)"
                    },
                    {
                        "in": "body",
                        "name": "password",
                        "required": true,
                        "type": "string",
                        "description": "패스워드"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success=성공. login_failed=로그인실패. token=인증토큰. message=메세지",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "success": true,
                                        "login_failed": false,
                                        "token": "asdqwjehsxmqwiuz,ruwoqi,zrojwqe.crovw.eo",
                                        "message": "foobar"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Parameter",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {}
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {}
                                }
                            }
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "put": {
                "tags": ["auth"],
                "summary": "액세스 토큰 갱신입니다..",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "in": "body",
                        "name": "email",
                        "required": true,
                        "type": "string",
                        "description": "사용자 아이디(이메일)"
                    },
                    {
                        "in": "body",
                        "name": "password",
                        "required": true,
                        "type": "string",
                        "description": "패스워드"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success=성공. expired=토큰 만료여부. access_token=액세스토큰. message=메세지",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "success": true,
                                        "expired": false,
                                        "access_token": "asdqwjehsxmqwiuz,ruwoqi,zrojwqe.crovw.eo",
                                        "message": "error"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Parameter",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {}
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {}
                                }
                            }
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "delete": {
                "tags": ["auth"],
                "summary": "로그아웃. 리프레시 토큰 삭제입니다. (인증 필요)",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "in": "body",
                        "name": "refresh_token",
                        "required": true,
                        "type": "string",
                        "description": "리프레시 토큰"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success=성공. message=메세지",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "success": true,
                                        "message": "foobar"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Parameter",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {}
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {}
                                }
                            }
                        }
                    }
                }
            }
        },
        "/user/my-info": {
            "get": {
                "tags": ["user"],
                "summary": "사용자 자신 정보 조회 (인증 필요)",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [],
                "responses": {
                    "200": {
                        "description": "success=성공. message=메세지. email=이메일. nickname=닉네임. reg_time=가입일시(UTC)",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "success": true,
                                        "message": "success",
                                        "email": "foobar@naver.com",
                                        "nickname": "asdf",
                                        "reg_time": 12321432132
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Parameter",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {}
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {}
                                }
                            }
                        }
                    }
                }
            }
        },
        "/user/close-my-account": {
            "delete": {
                "tags": ["user"],
                "summary": "회원 탈퇴",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [],
                "responses": {
                    "200": {
                        "description": "success=성공. message=메세지.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "success": true,
                                        "message": "success"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Parameter",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {}
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {}
                                }
                            }
                        }
                    }
                }
            }
        },
        "/doc/document": {
            "post": {
                "tags": ["doc"],
                "summary": "문서 등록 (인증 필요)",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "in": "body",
                        "name": "title",
                        "required": true,
                        "type": "string",
                        "description": "문서 제목"
                    },
                    {
                        "in": "body",
                        "name": "content",
                        "required": true,
                        "type": "string",
                        "description": "문서 내용"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success=성공. message=메세지. is_new_doc=신규등록인지.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "success": true,
                                        "is_new_doc": true,
                                        "message": "foobar"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Parameter",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {}
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {}
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "tags": ["doc"],
                "summary": "문서 조회",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "in": "query",
                        "name": "title",
                        "required": true,
                        "type": "string",
                        "description": "문서 제목"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success=성공. message=메세지. not_exists=문서없음. title=문서제목. last_update_utc=문서최근수정일",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "success": true,
                                        "not_exists": false,
                                        "title": "문서제목",
                                        "content": "으악",
                                        "last_update_utc": 54480055,
                                        "message": "foobar"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Parameter",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {}
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {}
                                }
                            }
                        }
                    }
                }
            }
        },
        "/file": {
            "post": {
                "tags": ["file"],
                "summary": "파일 업로드입니다. (미완성) (인증 필요)",
                "consumes": ["multipart/form-data"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "in": "body",
                        "name": "file",
                        "required": true,
                        "type": "file",
                        "description": "파일 데이터"
                    },
                    {
                        "in": "body",
                        "name": "title",
                        "required": true,
                        "type": "string",
                        "description": "파일 제목"
                    },
                    {
                        "in": "body",
                        "name": "content",
                        "required": false,
                        "type": "string",
                        "description": "파일 내용"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success=성공. file_write_failed=파일쓰기 실패. file_too_big=파일사이즈 초과. title_duplicate=파일명 중복",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "success": true,
                                        "file_write_failed": false,
                                        "file_too_big": false,
                                        "title_duplicate": false
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Parameter",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {}
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {}
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {}
                                }
                            }
                        }
                    }
                }
            },
            "put": {
                "tags": ["file"],
                "summary": "파일 문서 내용 수정입니다. (인증 필요)",
                "consumes": ["multipart/form-data"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "in": "body",
                        "name": "title",
                        "required": true,
                        "type": "string",
                        "description": "파일 제목"
                    },
                    {
                        "in": "body",
                        "name": "content",
                        "required": false,
                        "type": "string",
                        "description": "파일 내용"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success=성공. message=메세지",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "success": true,
                                        "message": ",..."
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Parameter",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {}
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {}
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {}
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "Response": {
        "JustSuccess": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        }
    }
}
